FROM node:latest
WORKDIR /usr/src/app
COPY package*.json /usr/src/app/
RUN npm install --production && npm install -g mocha
 # The <dest> in COPY is an absolute path, or a path relative to WORKDIR - we want the latter
COPY ./ ./
EXPOSE 8000
ENV NODE_ENV=test MONGO_URI__TEST=mongodb://mongo:27017/test JWT_SECRET=skrrrt
CMD ["mocha"]